// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM7ykdzu-kAyiI6KO77YXESdlapKGNLcA',
    appId: '1:138225201349:web:7753bb8dca7374061400ac',
    messagingSenderId: '138225201349',
    projectId: 'atw-signin-task',
    authDomain: 'atw-signin-task.firebaseapp.com',
    storageBucket: 'atw-signin-task.firebasestorage.app',
    measurementId: 'G-T1BT79NJ3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAkfByKiuNk1Q7zry46R9XRB62Ej58KEk',
    appId: '1:138225201349:android:37b1658daf0868f81400ac',
    messagingSenderId: '138225201349',
    projectId: 'atw-signin-task',
    storageBucket: 'atw-signin-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl3e0ib9F4hqqtwLP30dVAEja1ZYnA2zU',
    appId: '1:138225201349:ios:1f2d5813aa507f391400ac',
    messagingSenderId: '138225201349',
    projectId: 'atw-signin-task',
    storageBucket: 'atw-signin-task.firebasestorage.app',
    iosBundleId: 'com.example.atwSigninTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl3e0ib9F4hqqtwLP30dVAEja1ZYnA2zU',
    appId: '1:138225201349:ios:1f2d5813aa507f391400ac',
    messagingSenderId: '138225201349',
    projectId: 'atw-signin-task',
    storageBucket: 'atw-signin-task.firebasestorage.app',
    iosBundleId: 'com.example.atwSigninTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM7ykdzu-kAyiI6KO77YXESdlapKGNLcA',
    appId: '1:138225201349:web:b67c29d530e7b06a1400ac',
    messagingSenderId: '138225201349',
    projectId: 'atw-signin-task',
    authDomain: 'atw-signin-task.firebaseapp.com',
    storageBucket: 'atw-signin-task.firebasestorage.app',
    measurementId: 'G-S1F7Q5NDBW',
  );

}